### ISSUE TITLE
Delete QC folder?

### ISSUE THREAD

**Issue by wildingka** [PovertyAction/guides.github.io#2]
I think we should get rid of all of the programming utilities in the QC folder (ie. "Searching many do files", "Gathering file information for many files, "Finding differences between two do-files", "Cleaning up and REstyling do-files", and "comparing two excel files"). I actually don't remember how these got put back in as I had removed them from the guide. Most of these are do files/python scripts written by a previous RA and aren't very useful/functional. Also, some of these can be done in Stata do files themselves now (e.g. restyling). I also don't think these fit well with the purpose of the guide anymore.

**Comment by mfrosenbaum** [comment]
Per call, this will be removed from the guide.
