### ISSUE TITLE
De-Identifying Data - IPA PII Protocols link

### ISSUE THREAD

**Issue by rachelauryn** [PovertyAction/guides.github.io#9]
In [de-identifying data](https://povertyaction.github.io/guides.github.io/CleaningGuide/01%20Raw%20Survey%20Data%20Management/03%20De-identifying%20data.html), the link to "[see IPA’s protocols surrounding PII](https://github.com/PovertyAction/guides.github.io/edit/master/CleaningGuide/01%20Raw%20Survey%20Data%20Management/03%20De-identifying%20data.md)" took me to editing the page.

**Comment by mfrosenbaum** [comment]
I've fixed this link.
